import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Foooter from "./components/Foooter";

export const metadata: Metadata = {
  title: "Nanovision - Revolutionize Your Communication",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Navbar  */}
        <Navbar />
        {children}
        {/* Footer  */}
        <Foooter />
      </body>
    </html>
  );
}
